workflows:
  ios-workflow:
    name: iOS Workflow

    integrations:
      app_store_connect: poker-app-codemagic

    environment:
      flutter: stable
      xcode: latest
      ios_signing:
        distribution_type: app_store
        bundle_identifier: com.joetseng.pokertablereservation

    scripts:
      - flutter clean
      - flutter pub get
      - cd ios && pod install && cd ..
      - name: Set up code signing settings on Xcode project
        script: xcode-project use-profiles
      - flutter build ipa --release --export-method app-store

    artifacts:
      - build/ios/ipa/*.ipa

    publishing:
      app_store_connect:
        auth: integration
        submit_to_testflight: true