// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyD_lQtjqc2Jy_T1w10Pltb0Ju21xT7gD9s',
    appId: '1:1019034709236:web:0a4ae0a4cebb35d499c2a1',
    messagingSenderId: '1019034709236',
    projectId: 'poker-scheduler-fd8c7',
    authDomain: 'poker-scheduler-fd8c7.firebaseapp.com',
    storageBucket: 'poker-scheduler-fd8c7.firebasestorage.app',
    measurementId: 'G-W3BWTSSQJT',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAmDwku4yiCtjL_zh9zEjP7EU8I37XlRZw',
    appId: '1:1019034709236:android:7585f4efc82d47a599c2a1',
    messagingSenderId: '1019034709236',
    projectId: 'poker-scheduler-fd8c7',
    storageBucket: 'poker-scheduler-fd8c7.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCS4jV1lN8snhdEY1Y6rkSSgaB6eAetDAs',
    appId: '1:1019034709236:ios:36cbcc53231e3eb099c2a1',
    messagingSenderId: '1019034709236',
    projectId: 'poker-scheduler-fd8c7',
    storageBucket: 'poker-scheduler-fd8c7.firebasestorage.app',
    iosClientId: '1019034709236-o17jdnh3fki8qugu89905emcsb170gcr.apps.googleusercontent.com',
    iosBundleId: 'com.joetseng.pokertablereservation',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCS4jV1lN8snhdEY1Y6rkSSgaB6eAetDAs',
    appId: '1:1019034709236:ios:ba143d2b5a9cbca099c2a1',
    messagingSenderId: '1019034709236',
    projectId: 'poker-scheduler-fd8c7',
    storageBucket: 'poker-scheduler-fd8c7.firebasestorage.app',
    iosClientId: '1019034709236-7835ot7gnt2cjr98m1s39cuja3re3bun.apps.googleusercontent.com',
    iosBundleId: 'com.example.pokerScheduler',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyD_lQtjqc2Jy_T1w10Pltb0Ju21xT7gD9s',
    appId: '1:1019034709236:web:20ab014902f14d6d99c2a1',
    messagingSenderId: '1019034709236',
    projectId: 'poker-scheduler-fd8c7',
    authDomain: 'poker-scheduler-fd8c7.firebaseapp.com',
    storageBucket: 'poker-scheduler-fd8c7.firebasestorage.app',
    measurementId: 'G-70SB0NF1CL',
  );
}